executor: KubernetesExecutor

dags:
  gitSync:
    enabled: true
    repo: https://github.com/KinushDK/nyc-tlc-data-platform.git
    branch: main
    subPath: pipelines/orchestration/dags

webserver:
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 512Mi

scheduler:
  resources:
    requests:
      cpu: 100m
      memory: 768Mi
    limits:
      memory: 1024Mi

postgresql:
  primary:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi